import React, { createContext, useContext, useState, useEffect } from 'react';

export type Language = 'en' | 'te' | 'hi';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Landing & Auth
    app_title: "Farmer2Gov",
    tagline: "From Pre-Harvest Registration to Transparent Government Procurement.",
    select_language: "Select Language / భాషను ఎంచుకోండి / भाषा चुनें",
    farmer: "Farmer",
    officer: "Procurement Officer",
    admin: "Administrator",
    phone_number: "Mobile Number",
    otp_code: "OTP Code",
    send_otp: "Send OTP",
    verify_otp: "Verify OTP",
    otp_sent: "OTP Sent! Enter 123456 to log in.",
    sign_in: "Sign In",
    password: "Password",
    login_btn: "Login",
    logout: "Logout",

    // Landing Page sections
    hero_title: "Transparent & Direct Government Procurement",
    hero_subtitle: "An AI-powered coordination platform helping Indian farmers register pre-harvest crops, verify produce quality with computer vision, and secure direct government payments.",
    get_started: "Get Started",
    how_it_works: "How It Works",
    step1_title: "1. Pre-Harvest Registration",
    step1_desc: "Farmers register crops 1-2 months before harvest, allowing government centres to plan storage capacity.",
    step2_title: "2. Visual Quality Upload",
    step2_desc: "Upload produce images via smartphone camera. Our OpenCV processor estimates moisture and uniformity instantly.",
    step3_title: "3. Direct Verification",
    step3_desc: "Procurement officers inspect samples and record moisture and weight directly to the digital registry.",
    step4_title: "4. Direct Benefit Transfer",
    step4_desc: "Funds are directly disbursed to the farmer's Aadhaar-linked bank account within 3 days.",
    faq_title: "Frequently Asked Questions",
    statistics: "Statistics",
    farmers_registered: "Farmers Registered",
    procured_qty: "Procured Quantity",
    msp_paid: "Direct Payments Paid",

    // Farmer Dashboard & Navigation
    farmer_dashboard: "Farmer Dashboard",
    register_crop: "Register Crop",
    sell_produce: "Sell Produce",
    msp_info: "MSP Information",
    my_procurement: "My Procurement",
    payment_tracking: "Payment Tracking",
    voice_assistant: "Voice Assistant",
    recent_activities: "Recent Activities",
    timeline_status: "Status Timeline",
    gov_updates: "Government Updates",
    weather_info: "Weather Info",
    crop_name: "Crop Name",
    expected_harvest: "Expected Harvest Month",
    expected_qty: "Expected Quantity (Quintals)",
    land_area: "Land Area (Acres)",
    state: "State",
    district: "District",
    mandal: "Mandal",
    village: "Village",
    submit_reg: "Submit Registration",
    crop_ready: "Produce Ready",
    capture_images: "Capture Produce Images",
    full_view: "Full Produce View",
    closeup_view: "Close-up View",
    storage_view: "Storage View",
    camera_btn: "Simulate Capture",
    submit_images: "Submit Photos",
    run_ai_analysis: "Run AI Quality Pre-Assessment",
    ai_disclaimer: "Disclaimer: Final procurement approval is performed only by authorized procurement officials.",
    visual_score: "AI Visual Score",
    moisture_est: "Estimated Moisture",
    uniformity: "Grain Uniformity",
    foreign_matter: "Foreign Material",
    recommendation: "AI Recommendation",
    slot_booking: "Procurement Slot Booking",
    select_slot: "Select Preferred Slot",
    book_slot: "Confirm Slot Booking",
    txn_id: "Transaction ID",
    expected_payment_date: "Expected Date",
    payment_status: "Payment Status",
    voice_btn_start: "Tap to Speak",
    voice_btn_listening: "Listening...",
    voice_prompt: "Speak now (e.g., 'Is my payment completed?', 'నా డబ్బులు వచ్చాయా?', 'मेरा भुगतान हो गया क्या?')",

    // Status mapping
    status_registered: "Registered",
    status_uploaded: "Images Uploaded",
    status_ai_reviewed: "AI Reviewed",
    status_approved: "Approved",
    status_slot_booked: "Slot Booked",
    status_procured: "Procured",
    status_payment_completed: "Payment Completed",

    // Custom Phase 1 & 2 additions
    nav_my_registrations: "My Registrations",
    nav_register_crop: "Register Crop",
    nav_register_produce: "Register Produce",
    nav_msp_info: "MSP Information",
    nav_my_procurement: "My Procurement & Tracking",
    welcome_back: "Welcome back",
    active_registrations_title: "My Crop & Produce Registrations",
    no_active_registrations: "No active registrations found.",
    no_active_registrations_desc: "Submit crop pre-harvest or harvested produce form to get started.",
    quick_actions: "Quick Actions",
    gov_bulletins: "Government Updates",
    bulletin_1: "Subsidized seeds distribution starting July 20 at local PACS centres.",
    bulletin_2: "MSP procurement centers in Warangal now accept direct harvested registrations.",
    farmer_portal: "Farmer Portal",
    back_to_dashboard: "Back to Dashboard",
    registration_details: "Registration Details",
    farmer_contact: "Farmer Contact",
    state_location: "State / Location",
    category: "Category",
    harvest_date: "Harvest Date",
    visual_assessment_title: "Visual Assessment Quality Check",
    visual_assessment_desc: "Upload a single produce photo for preliminary AI moisture estimation and crop quality grade assessment.",
    live_camera: "Live Camera",
    local_upload: "Local Upload",
    upload_location: "Upload Location",
    image_capture_location: "Image Capture Location",
    capture_timestamp: "Capture Timestamp",
    upload_time: "Upload Time",
    ai_pre_assessment_report: "AI Pre-Assessment Report",
    quality: "Quality",
    moisture: "Moisture",
    purity: "Purity",
    uniformity_metric: "Uniformity",
    reinspection_required_msg: "Reinspection requested: please review instructions.",
    inspect_crop_sample: "Inspect Crop Sample",
    perform_weigh_in: "Perform Weigh-In & Procure",
    booking_eligibility_error: "Procurement approval is required before booking a slot.",
    booking_slots_title: "Available Procurement Slots",
    confirm_booking: "Confirm Booking",
    booking_success: "Slot Booked Successfully",
    booking_receipt_title: "Procurement Slot Booking Receipt",
    farmer_name: "Farmer Name",
    registration_id: "Registration ID",
    procurement_id: "Procurement ID",
    procurement_centre: "Procurement Centre",
    date: "Date",
    time: "Time",
    booking_status: "Booking Status",
    print_receipt: "Print Receipt",
    download_receipt: "Download / Save Receipt",
    back_btn: "Back",
    pre_harvest_receipt_title: "Pre-Harvest Registration Receipt",
    produce_receipt_title: "Produce Registration Receipt",
    registered_successfully: "Registration Successful",
    expected_qty_qtl: "Expected Quantity (Qtl)",
    quantity_qtl: "Quantity (Qtl)",
    registration_date: "Registration Date",
    current_status: "Current Status",
    produce_image_assessment_disclaimer: "This is an AI-assisted preliminary visual assessment. Final quality verification is performed by the procurement officer.",
    image_verification_btn: "Capture/Upload Photo",
    image_source_label: "Image Source",
    capture_photo_option: "Capture Live Photo",
    upload_photo_option: "Upload Local Image",
    select_image_file: "Select Image File",
    status_timeline: "Status Timeline",
    search_crop: "Search produce...",
    all_categories: "All",
    grains: "Grains",
    pulses: "Pulses",
    vegetables: "Vegetables",
    oilseeds: "Oilseeds",
    commercial_crops: "Commercial Crops",
    msp_rate_label: "Government MSP",
    demo_price_label: "Demo Market Price",
    prototype_price_data: "Prototype Price Data",
    payment_expected_payout: "Expected Payout",
    payment_transaction_ref: "Transaction Reference",
    payment_timeline: "Payment Timeline",
    weigh_in_completed: "Weigh-In Completed",
    payment_initiated: "Payment Initiated",
    untranslated_notice: "This is a prototype estimate.",
    slot_booking_title: "Government Procurement Slot Booking",
    select_registration_label: "Select Crop / Produce Registration",
    select_option_placeholder: "Choose a Registration",
    booking_restricted_title: "Slot Booking Unavailable",
    slot_booked_receipt: "Slot Booking Confirmed",
    weigh_in_schedule: "Slot Timing",
    close: "Close",
    approved_qty: "Approved Quantity",
    select_date_label: "Select Appointment Date",
    select_time_label: "Select Time Window",
    confirm_booking_btn: "Confirm Slot Booking",
    pricing_hub_title: "Agricultural Pricing & MSP Information Hub",
    pricing_hub_desc: "Review government Minimum Support Prices (MSP) and local market pricing updates.",
    demo_warning_banner: "Demo Price Data. Values are for reference....",
    price_label: "Price",

    // Crops translations
    crop_paddy: "Paddy",
    crop_wheat: "Wheat",
    crop_maize: "Maize",
    crop_jowar: "Jowar",
    crop_bajra: "Bajra",
    crop_ragi: "Ragi",
    crop_gram: "Gram",
    crop_tur: "Tur (Arhar)",
    crop_moong: "Moong",
    crop_urad: "Urad",
    crop_groundnut: "Groundnut",
    crop_sunflower_seed: "Sunflower Seed",
    crop_soybean: "Soybean",
    crop_sesamum: "Sesamum",
    crop_cotton: "Cotton",
    crop_tomato: "Tomato",
    crop_onion: "Onion",
    crop_potato: "Potato",
    crop_chilli: "Chilli",
    crop_turmeric: "Turmeric",

    // Crop Info & Descriptions translations
    crop_paddy_info: "Primary kharif cereal. Government guaranteed MSP.",
    crop_wheat_info: "Rabi staple crop. Government guaranteed MSP.",
    crop_maize_info: "Coarse cereal used for feed & food. Government MSP.",
    crop_jowar_info: "Sorghum millet, highly drought resistant. Government MSP.",
    crop_bajra_info: "Pearl millet staple. Government MSP.",
    crop_ragi_info: "Finger millet, high calcium. Government MSP.",
    crop_gram_info: "Chickpea rabi pulse. Government MSP.",
    crop_tur_info: "Pigeon pea kharif pulse. Government MSP.",
    crop_moong_info: "Green gram pulse. Government MSP.",
    crop_urad_info: "Black gram pulse. Government MSP.",
    crop_groundnut_info: "Peanut oilseed crop. Government MSP.",
    crop_sunflower_seed_info: "High oil yield seed crop. Government MSP.",
    crop_soybean_info: "Yellow soybean oilseed. Government MSP.",
    crop_sesamum_info: "Sesame til crop. Government MSP.",
    crop_cotton_info: "Fiber cash crop. Government MSP.",
    crop_tomato_info: "Daily vegetable produce. Market Price / Demo Data.",
    crop_onion_info: "Staple kitchen vegetable. Market Price / Demo Data.",
    crop_potato_info: "Tubers cash crop. Market Price / Demo Data.",
    crop_chilli_info: "Red spice crop. Market Price / Demo Data.",
    crop_turmeric_info: "Spices cash crop. Market Price / Demo Data.",

    // Category key translations
    cat_grains: "Grains",
    cat_pulses: "Pulses",
    cat_vegetables: "Vegetables",
    cat_oilseeds: "Oilseeds",
    cat_commercial: "Commercial Crops",

    // Units translations
    unit_qtl: "per Quintal",
  },
  te: {
    app_title: "రైతుసేవ గవ్",
    tagline: "పంట ముందస్తు నమోదు నుండి పారదర్శక ప్రభుత్వ కొనుగోలు వరకు.",
    select_language: "భాషను ఎంచుకోండి",
    farmer: "రైతు",
    officer: "కొనుగోలు అధికారి",
    admin: "అడ్మినిస్ట్రేటర్",
    phone_number: "మొబైల్ సంఖ్య",
    otp_code: "ఓటిపి కోడ్",
    send_otp: "ఓటిపి పంపండి",
    verify_otp: "ఓటిపి వెరిఫై చేయండి",
    otp_sent: "ఓటిపి పంపబడింది! లాగిన్ అవ్వడానికి 123456 నొక్కండి.",
    sign_in: "సైన్ ఇన్ చేయండి",
    password: "పాస్వర్డ్",
    login_btn: "లాగిన్",
    logout: "లాగ్ అవుట్",

    hero_title: "పారదర్శక మరియు ప్రత్యక్ష ప్రభుత్వ కొనుగోలు",
    hero_subtitle: "భారతీయ రైతులకు పంట నమోదు, కంప్యూటర్ విజన్ నాణ్యత తనిఖీ మరియు నేరుగా ప్రభుత్వ చెల్లింపులు అందజేసే ఒక వినూత్న డిజిటల్ పబ్లిక్ ఇన్ఫ్రాస్ట్రక్చర్.",
    get_started: "ప్రారంభించండి",
    how_it_works: "ఇది ఎలా పనిచేస్తుంది",
    step1_title: "1. పంట ముందస్తు నమోదు",
    step1_desc: "రైతులు పంట కోతకు 1-2 నెలల ముందే వివరాలు నమోదు చేసి ప్రభుత్వ కొనుగోలు ప్రణాళికకు సహాయపడతారు.",
    step2_title: "2. నాణ్యత చిత్రాల అప్‌లోడ్",
    step2_desc: "మొబైల్ కెమెరాతో పంట ఫోటోలను అప్‌లోడ్ చేయండి. మా OpenCV సిస్టమ్ తేమ శాతాన్ని తక్షణమే లెక్కిస్తుంది.",
    step3_title: "3. ప్రత్యక్ష నాణ్యత నిర్ధారణ",
    step3_desc: "అధికారులు నమూనాలను తనిఖీ చేసి, తేమ మరియు బరువును డిజిటల్ రిజిస్టర్‌లో నమోదు చేస్తారు.",
    step4_title: "4. నేరుగా ఖాతాలోకి చెల్లింపు",
    step4_desc: "డబ్బులు నేరుగా రైతు ఆధార్ అనుసంధాన బ్యాంక్ ఖాతాకు 3 రోజుల్లో జమ చేయబడతాయి.",
    faq_title: "తరచుగా అడిగే ప్రశ్నలు",
    statistics: "గణాంకాలు",
    farmers_registered: "నమోదైన రైతులు",
    procured_qty: "కొనుగోలు చేసిన పరిమాణం",
    msp_paid: "చెల్లించిన మొత్తం",

    farmer_dashboard: "రైతు డాష్‌బోర్డ్",
    register_crop: "పంట నమోదు",
    sell_produce: "పంట విక్రయం",
    msp_info: "కనీస మద్దతు ధర (MSP)",
    my_procurement: "నా కొనుగోలు",
    payment_tracking: "చెల్లింపు ట్రాకింగ్",
    voice_assistant: "వాయిస్ అసిస్టెంట్",
    recent_activities: "ఇటీవలి చర్యలు",
    timeline_status: "స్థితి టైమ్‌లైన్",
    gov_updates: "ప్రభుత్వ సమాచారం",
    weather_info: "వాతావరణ సమాచారం",
    crop_name: "పంట పేరు",
    expected_harvest: "కోత సమయం (నెల)",
    expected_qty: "ఆశించిన దిగుబడి (క్వింటాళ్ళు)",
    land_area: "భూమి విస్తీర్ణం (ఎకరాలు)",
    state: "రాష్ట్రం",
    district: "జిల్లా",
    mandal: "మండలం",
    village: "గ్రామం",
    submit_reg: "నమోదును సమర్పించండి",
    crop_ready: "పంట సిద్ధంగా ఉంది",
    capture_images: "పంట ఫోటోలు తీయండి",
    full_view: "పంట పూర్తి వ్యూ",
    closeup_view: "క్లోజ్-అప్ వ్యూ",
    storage_view: "నిల్వ ఉంచిన వ్యూ",
    camera_btn: "ఫోటో తీయండి",
    submit_images: "ఫోటోలు సమర్పించండి",
    run_ai_analysis: "నాణ్యత తనిఖీ ప్రారంభించు",
    ai_disclaimer: "గమనిక: కొనుగోలుకు తుది ఆమోదం కేవలం అధికారిక కొనుగోలు అధికారుల ద్వారా మాత్రమే జరుగుతుంది.",
    visual_score: "AI నాణ్యత స్కోరు",
    moisture_est: "అంచనా తేమ శాతం",
    uniformity: "గింజ ఏకరూపత",
    foreign_matter: "చెత్త చెదారం",
    recommendation: "AI సిఫార్సు",
    slot_booking: "కొనుగోలు స్లాట్ బుకింగ్",
    select_slot: "స్లాట్ సమయం ఎంచుకోండి",
    book_slot: "స్లాట్ నిర్ధారించండి",
    txn_id: "ట్రాన్సాక్షన్ ఐడి",
    expected_payment_date: "ఆశించిన తేది",
    payment_status: "చెల్లింపు స్థితి",
    voice_btn_start: "మాట్లాడటానికి నొక్కండి",
    voice_btn_listening: "వింటున్నాను...",
    voice_prompt: "ఇప్పుడు మాట్లాడండి (ఉదా: 'నా డబ్బులు వచ్చాయా?', 'నా స్థితి ఏమిటి?')",

    status_registered: "నమోదైంది",
    status_uploaded: "ఫోటోలు అప్‌లోడ్ అయ్యాయి",
    status_ai_reviewed: "AI సమీక్ష పూర్తయింది",
    status_approved: "ఆమోదించబడింది",
    status_slot_booked: "స్లాట్ బుక్ అయింది",
    status_procured: "కొనుగోలు పూర్తయింది",
    status_payment_completed: "చెల్లింపు పూర్తయింది",

    nav_my_registrations: "నా నమోదులు",
    nav_register_crop: "పంట ముందస్తు నమోదు",
    nav_register_produce: "పంట విక్రయం",
    nav_msp_info: "మద్దతు ధరల సమాచారం",
    nav_my_procurement: "నా కొనుగోలు & ట్రాకింగ్",
    welcome_back: "స్వాగతం",
    active_registrations_title: "నా పంట & విక్రయ నమోదు వివరాలు",
    no_active_registrations: "నా యాక్టివ్ నమోదులు ఏవీ లేవు.",
    no_active_registrations_desc: "ప్రారంభించడానికి పంట ముందస్తు నమోదు లేదా పంట విక్రయ వివరాలు సమర్పించండి.",
    quick_actions: "త్వరిత చర్యలు",
    gov_bulletins: "ప్రభుత్వ తాజా వార్తలు",
    bulletin_1: "సబ్సిడీ విత్తనాల పంపిణీ జూలై 20 నుండి స్థానిక PACS కేంద్రాలలో ప్రారంభమౌతుంది.",
    bulletin_2: "ప్రభుత్వ కొనుగోలు కేంద్రాలలో ఇప్పుడు పంట విక్రయం నేరుగా ఆమోదించబడుతుంది.",
    farmer_portal: "రైతు పోర్టల్",
    back_to_dashboard: "డాష్‌బోర్డ్‌కు తిరిగి వెళ్ళు",
    registration_details: "నమోదు వివరాలు",
    farmer_contact: "రైతు ఫోన్ నెంబర్",
    state_location: "రాష్ట్రం / ప్రాంతం",
    category: "రకం",
    harvest_date: "కోత కోసిన తేది",
    visual_assessment_title: "నాణ్యత పరీక్ష",
    visual_assessment_desc: "పంట తేమ శాతం మరియు నాణ్యత అంచనా కోసం ఒక ఫోటోను అప్‌లోడ్ చేయండి.",
    live_camera: "లైవ్ కెమెరా",
    local_upload: "లోకల్ అప్‌లోడ్",
    upload_location: "అప్‌లోడ్ ప్రాంతం",
    image_capture_location: "ఫోటో తీసిన ప్రాంతం",
    capture_timestamp: "ఫోటో తీసిన సమయం",
    upload_time: "అప్‌లోడ్ చేసిన సమయం",
    ai_pre_assessment_report: "AI నాణ్యత నివేదిక",
    quality: "నాణ్యత",
    moisture: "తేమ శాతం",
    purity: "స్వచ్ఛత",
    uniformity_metric: "ఏకరూపత",
    reinspection_required_msg: "పునఃపరిశీలన అవసరం: దయచేసి సూచనలను చూడండి.",
    inspect_crop_sample: "నమూనా నాణ్యత తనిఖీ",
    perform_weigh_in: "తూకం వేసి కొనుగోలు చేయి",
    booking_eligibility_error: "స్లాట్ బుక్ చేయడానికి ముందు ప్రభుత్వ కొనుగోలు అధికారి ఆమోదం అవసరం.",
    booking_slots_title: "అందుబాటులో ఉన్న కొనుగోలు స్లాట్లు",
    confirm_booking: "స్లాట్ బుకింగ్ నిర్ధారించు",
    booking_success: "స్లాట్ విజయవంతంగా బుక్ అయింది",
    booking_receipt_title: "కొనుగోలు స్లాట్ బుకింగ్ రసీదు",
    farmer_name: "రైతు పేరు",
    registration_id: "నమోదు ఐడి",
    procurement_id: "కొనుగోలు ఐడి",
    procurement_centre: "కొనుగోలు కేంద్రం",
    date: "తేది",
    time: "సమయం",
    booking_status: "బుకింగ్ స్థితి",
    print_receipt: "రసీదు ముద్రించు",
    download_receipt: "రసీదు సేవ్ చేయి",
    back_btn: "వెనుకకు",
    pre_harvest_receipt_title: "పంట ముందస్తు నమోదు రసీదు",
    produce_receipt_title: "పంట విక్రయ నమోదు రసీదు",
    registered_successfully: "నమోదు విజయవంతమైంది",
    expected_qty_qtl: "ఆశించిన పరిమాణం (క్వింటాళ్ళు)",
    quantity_qtl: "పరిమాణం (క్వింటాళ్ళు)",
    registration_date: "నమోదు తేది",
    current_status: "ప్రస్తుత స్థితి",
    produce_image_assessment_disclaimer: "ఇది కేవలం ప్రాథమిక అంచనా నివేదిక మాత్రమే. తుది నాణ్యత ఆమోదం కొనుగోలు అధికారి ద్వారా మాత్రమే జరుగుతుంది.",
    image_verification_btn: "ఫోటో తీయి/అప్‌లోడ్ చేయి",
    image_source_label: "ఫోటో మూలం",
    capture_photo_option: "లైవ్ ఫోటో తీయండి",
    upload_photo_option: "లోకల్ అప్‌లోడ్ చేయండి",
    select_image_file: "ఫైల్ ఎంచుకోండి",
    status_timeline: "స్థితి టైమ్‌లైన్",
    search_crop: "పంటల శోధన...",
    all_categories: "అన్నీ",
    grains: "ధాన్యాలు",
    pulses: "పప్పుధాన్యాలు",
    vegetables: "కూరగాయలు",
    oilseeds: "నూనె గింజలు",
    commercial_crops: "వాణిజ్య పంటలు",
    msp_rate_label: "ప్రభుత్వ మద్దతు ధర",
    demo_price_label: "మార్కెట్ ధర (అంచనా)",
    prototype_price_data: "మార్కెట్ ధర సమాచారం",
    payment_expected_payout: "ఆశించిన మొత్తం",
    payment_transaction_ref: "లావాదేవీ సంఖ్య",
    payment_timeline: "చెల్లింపు టైమ్‌లైన్",
    weigh_in_completed: "తూకం పూర్తయింది",
    payment_initiated: "చెల్లింపు ప్రారంభమైంది",
    untranslated_notice: "ఇది కేవలం ప్రదర్శన కోసం మాత్రమే.",
    slot_booking_title: "ప్రభుత్వ కొనుగోలు స్లాట్ బుకింగ్",
    select_registration_label: "పంట నమోదును ఎంచుకోండి",
    select_option_placeholder: "నమోదును ఎంచుకోండి",
    booking_restricted_title: "స్లాట్ బుకింగ్ అందుబాటులో లేదు",
    slot_booked_receipt: "స్లాట్ విజయవంతంగా బుక్ అయింది",
    weigh_in_schedule: "స్లాట్ సమయం",
    close: "మూసివేయి",
    approved_qty: "ఆమోదించబడిన పరిమాణం",
    select_date_label: "తేది ఎంచుకోండి",
    select_time_label: "సమయం ఎంచుకోండి",
    confirm_booking_btn: "స్లాట్ బుకింగ్ నిర్ధారించు",
    pricing_hub_title: "వ్యవసాయ ధరలు & మద్దతు ధరల సమాచారం",
    pricing_hub_desc: "ప్రభుత్వ కనీస మద్దతు ధరలు (MSP) మరియు మార్కెట్ ధరలను పరిశీలించండి.",
    demo_warning_banner: "ధరల సమాచారం కేవలం డెమో కొరకు మాత్రమే.",
    price_label: "ధర",

    crop_paddy: "వరి",
    crop_wheat: "గోధుమ",
    crop_maize: "మొక్కజొన్న",
    crop_jowar: "జొన్నలు",
    crop_bajra: "సజ్జలు",
    crop_ragi: "రాగులు",
    crop_gram: "శనగలు",
    crop_tur: "కందులు",
    crop_moong: "పెసలు",
    crop_urad: "మినుములు",
    crop_groundnut: "వేరుశనగ",
    crop_sunflower_seed: "పొద్దుతిరుగుడు గింజలు",
    crop_soybean: "సోయాబీన్",
    crop_sesamum: "nuvvulu",
    crop_cotton: "పత్తి",
    crop_tomato: "టమోటా",
    crop_onion: "ఉల్లిపాయలు",
    crop_potato: "బంగాళదుంపలు",
    crop_chilli: "మిరపకాయలు",
    crop_turmeric: "పసుపు",

    crop_paddy_info: "ముఖ్యమైన ఖరీఫ్ పంట. ప్రభుత్వ మద్దతు ధర లభిస్తుంది.",
    crop_wheat_info: "రబీ ముఖ్యమైన పంట. ప్రభుత్వ మద్దతు ధర లభిస్తుంది.",
    crop_maize_info: "పశుగ్రాసం మరియు ఆహారంగా ఉపయోగించే పంట. ప్రభుత్వ మద్దతు ధర ఉంటుంది.",
    crop_jowar_info: "అత్యధిక కరువు తట్టుకునే జొన్న పంట. ప్రభుత్వ మద్దతు ధర ఉంటుంది.",
    crop_bajra_info: "సజ్జల సాగు. ప్రభుత్వ మద్దతు ధర లభిస్తుంది.",
    crop_ragi_info: "కాల్షియం అధికంగా ఉండే రాగులు. ప్రభుత్వ మద్దతు ధర ఉంటుంది.",
    crop_gram_info: "శనగల సాగు. ప్రభుత్వ మద్దతు ధర ఉంటుంది.",
    crop_tur_info: "కందుల సాగు. ప్రభుత్వ మద్దతు ధర ఉంటుంది.",
    crop_moong_info: "పెసల సాగు. ప్రభుత్వ మద్దతు ధర ఉంటుంది.",
    crop_urad_info: "మినుముల సాగు. ప్రభుత్వ మద్దతు ధర ఉంటుంది.",
    crop_groundnut_info: "నూనె గింజల పంట. ప్రభుత్వ మద్దతు ధర ఉంటుంది.",
    crop_sunflower_seed_info: "అధిక నూనె దిగుబడినిచ్చే పొద్దుతిరుగుడు. ప్రభుత్వ మద్దతు ధర ఉంటుంది.",
    crop_soybean_info: "సోయాబీన్ సాగు. ప్రభుత్వ మద్దతు ధర ఉంటుంది.",
    crop_sesamum_info: "nuvvula panta. ప్రభుత్వ మద్దతు ధర ఉంటుంది.",
    crop_cotton_info: "పీచు నాణ్యత గల పత్తి పంట. ప్రభుత్వ మద్దతు ధర ఉంటుంది.",
    crop_tomato_info: "రోజువారీ కూరగాయల పంట. మార్కెట్ ధర డెమో డేటా.",
    crop_onion_info: "కూరగాయల పంట. మార్కెట్ ధర డెమో డేటా.",
    crop_potato_info: "దుంపల పంట. మార్కెట్ ధర డెమో డేటా.",
    crop_chilli_info: "మిరప పంట. మార్కెట్ ధర డెమో డేటా.",
    crop_turmeric_info: "పసుపు పంట. మార్కెట్ ధర డెమో డేటా.",

    cat_grains: "ధాన్యాలు",
    cat_pulses: "పప్పుధాన్యాలు",
    cat_vegetables: "కూరగాయలు",
    cat_oilseeds: "నూనె గింజలు",
    cat_commercial: "వాణిజ్య పంటలు",
    unit_qtl: "క్వింటాల్ కు",
  },
  hi: {
    app_title: "कृषक2गव",
    tagline: "फसल पूर्व पंजीकरण से पारदर्शी सरकारी खरीद तक।",
    select_language: "भाषा चुनें",
    farmer: "किसान",
    officer: "खरीद अधिकारी",
    admin: "प्रशासक",
    phone_number: "मोबाइल नंबर",
    otp_code: "ओटीपी कोड",
    send_otp: "ओटीपी भेजें",
    verify_otp: "ओटीपी सत्यापित करें",
    otp_sent: "ओटीपी भेजा गया! लॉगिन करने के लिए 123456 दर्ज करें।",
    sign_in: "साइन इन करें",
    password: "पासवर्ड",
    login_btn: "लॉगिन",
    logout: "लॉग आउट",

    hero_title: "पारदर्शी और प्रत्यक्ष सरकारी खरीद",
    hero_subtitle: "भारतीय किसानों के लिए एक उन्नत डिजिटल पब्लिक इंफ्रास्ट्रक्चर जो फसल पूर्व पंजीकरण, कंप्यूटर विज़न आधारित गुणवत्ता परीक्षण और सीधे बैंक खाते में भुगतान सुनिश्चित करता है।",
    get_started: "शुरू करें",
    how_it_works: "यह कैसे काम करता है",
    step1_title: "1. फसल पूर्व पंजीकरण",
    step1_desc: "किसान कटाई से 1-2 महीने पहले पंजीकरण करते हैं, जिससे खरीद केंद्र भंडारण क्षमता की योजना बना सकते हैं।",
    step2_title: "2. गुणवत्ता छवियों का अपलोड",
    step2_desc: "स्मार्टफोन कैमरा से फसल की तस्वीरें अपलोड करें। हमारी प्रणाली नमी और अनाज एकरूपता का तुरंत विश्लेषण करती है।",
    step3_title: "3. प्रत्यक्ष सत्यापन",
    step3_desc: "खरीद अधिकारी नमूने का भौतिक निरीक्षण करते हैं और नमी व वास्तविक वजन डिजिटल रजिस्ट्री में दर्ज करते हैं।",
    step4_title: "4. प्रत्यक्ष लाभ हस्तांतरण",
    step4_desc: "राशि सीधे किसान के आधार-लिंक बैंक खाते में 3 दिनों के भीतर जमा कर दी जाती है।",
    faq_title: "अक्सर पूछे जाने वाले प्रश्न",
    statistics: "आंकड़े",
    farmers_registered: "पंजीकृत किसान",
    procured_qty: "खरीदी गई मात्रा",
    msp_paid: "भुगतान की गई राशि",

    farmer_dashboard: "किसान डैशबोर्ड",
    register_crop: "फसल पंजीकरण",
    sell_produce: "फसल बेचें",
    msp_info: "न्यूनतम समर्थन मूल्य (MSP)",
    my_procurement: "मेरी खरीद",
    payment_tracking: "भुगतान की स्थिति",
    voice_assistant: "आवाज सहायक",
    recent_activities: "हाल की गतिविधियां",
    timeline_status: "स्थिति टाइमलाइन",
    gov_updates: "सरकारी अपडेट",
    weather_info: "मौसम की जानकारी",
    crop_name: "फसल का नाम",
    expected_harvest: "अनुमानित कटाई का महीना",
    expected_qty: "अनुमानित मात्रा (क्विंटल)",
    land_area: "भूमि क्षेत्र (एकड़)",
    state: "राज्य",
    district: "जिला",
    mandal: "मंडल",
    village: "गांव",
    submit_reg: "पंजीकरण जमा करें",
    crop_ready: "फसल तैयार है",
    capture_images: "तस्वीरें लें",
    full_view: "फसल की पूरी तस्वीर",
    closeup_view: "क्लोज-अप तस्वीर",
    storage_view: "भंडारण तस्वीर",
    camera_btn: "तस्वीर खींचें",
    submit_images: "तस्वीरें जमा करें",
    run_ai_analysis: "एआई गुणवत्ता जांच चलाएं",
    ai_disclaimer: "अस्वीकरण: अंतिम खरीद स्वीकृति केवल अधिकृत खरीद अधिकारियों द्वारा ही की जाती है।",
    visual_score: "एआई गुणवत्ता स्कोर",
    moisture_est: "अनुमानित नमी",
    uniformity: "अनाज एकरूपता",
    foreign_matter: "विदेशी पदार्थ",
    recommendation: "एआई सिफारिश",
    slot_booking: "खरीद स्लॉट बुकिंग",
    select_slot: "पसंदीदा स्लॉट चुनें",
    book_slot: "स्लॉट बुक करें",
    txn_id: "लेनदेन आईडी",
    expected_payment_date: "संभावित तिथि",
    payment_status: "भुगतान स्थिति",
    voice_btn_start: "बोलने के लिए टैप करें",
    voice_btn_listening: "सुन रहा हूँ...",
    voice_prompt: "अब बोलें (जैसे, 'मेरा पैसा आया क्या?', 'मेरी फसल की स्थिति क्या है?')",

    status_registered: "पंजीकृत",
    status_uploaded: "तस्वीरें अपलोड की गईं",
    status_ai_reviewed: "एआई द्वारा समीक्षित",
    status_approved: "स्वीकृत",
    status_slot_booked: "स्लॉट बुक किया गया",
    status_procured: "खरीदी गई",
    status_payment_completed: "भुगतान पूर्ण",

    nav_my_registrations: "मेरे पंजीकरण",
    nav_register_crop: "फसल पूर्व पंजीकरण",
    nav_register_produce: "फसल बेचना",
    nav_msp_info: "समर्थन मूल्य की जानकारी",
    nav_my_procurement: "मेरी खरीद और ट्रैकिंग",
    welcome_back: "आपका स्वागत है",
    active_registrations_title: "मेरी फसल और उत्पाद पंजीकरण विवरण",
    no_active_registrations: "कोई सक्रिय पंजीकरण नहीं मिला।",
    no_active_registrations_desc: "शुरू करने के लिए फसल पूर्व पंजीकरण या फसल उत्पाद विवरण जमा करें।",
    quick_actions: "त्वरित कार्रवाई",
    gov_bulletins: "सरकारी सूचनाएं",
    bulletin_1: "रियायती बीजों का वितरण 20 जुलाई से स्थानीय PACS केंद्रों पर शुरू होगा।",
    bulletin_2: "वारंगल खरीद केंद्रों में अब फसल उत्पाद का सीधे पंजीकरण स्वीकार किया जा रहा है।",
    farmer_portal: "किसान पोर्टल",
    back_to_dashboard: "डैशबोर्ड पर वापस जाएं",
    registration_details: "पंजीकरण विवरण",
    farmer_contact: "किसान का फोन नंबर",
    state_location: "राज्य / स्थान",
    category: "श्रेणी",
    harvest_date: "कटाई की तारीख",
    visual_assessment_title: "गुणवत्ता परीक्षण",
    visual_assessment_desc: "प्राथमिक एआई नमी और गुणवत्ता आकलन के लिए एक तस्वीर अपलोड करें।",
    live_camera: "लाइव कैमरा",
    local_upload: "लोकल अपलोड",
    upload_location: "अपलोड स्थान",
    image_capture_location: "तस्वीर खींचने का स्थान",
    capture_timestamp: "तस्वीर खींचने का समय",
    upload_time: "अपलोड करने का समय",
    ai_pre_assessment_report: "एआई गुणवत्ता रिपोर्ट",
    quality: "गुणवत्ता",
    moisture: "नमी",
    purity: "शुद्धता",
    uniformity_metric: "एकरूपता",
    reinspection_required_msg: "पुनः निरीक्षण की आवश्यकता: कृपया निर्देशों की समीक्षा करें।",
    inspect_crop_sample: "नमूना गुणवत्ता जांच",
    perform_weigh_in: "तौल कर खरीद करें",
    booking_eligibility_error: "स्लॉट बुक करने से पहले खरीद अधिकारी की स्वीकृति आवश्यक है।",
    booking_slots_title: "उपलब्ध सरकारी खरीद स्लॉट",
    confirm_booking: "स्लॉट बुकिंग की पुष्टि करें",
    booking_success: "स्लॉट सफलतापूर्वक बुक हो गया है",
    booking_receipt_title: "खरीद स्लॉट बुकिंग रसीद",
    farmer_name: "किसान का नाम",
    registration_id: "पंजीकरण आईडी",
    procurement_id: "खरीद आईडी",
    procurement_centre: "खरीद केंद्र",
    date: "तारीख",
    time: "समय",
    booking_status: "बुकिंग की स्थिति",
    print_receipt: "रसीद प्रिंट करें",
    download_receipt: "रसीद सहेजें",
    back_btn: "पीछे",
    pre_harvest_receipt_title: "फसल पूर्व पंजीकरण रसीद",
    produce_receipt_title: "फसल पंजीकरण रसीद",
    registered_successfully: "पंजीकरण सफल रहा",
    expected_qty_qtl: "अनुमानित मात्रा (क्विंटल)",
    quantity_qtl: "मात्रा (क्विंटल)",
    registration_date: "पंजीकरण तिथि",
    current_status: "वर्तमान स्थिति",
    produce_image_assessment_disclaimer: "यह एआई आधारित गुणवत्ता आकलन है। अंतिम गुणवत्ता सत्यापन खरीद अधिकारी द्वारा किया जाएगा।",
    image_verification_btn: "तस्वीर लें/अपलोड करें",
    image_source_label: "तस्वीर का स्रोत",
    capture_photo_option: "लाइव तस्वीर लें",
    upload_photo_option: "लोकल अपलोड करें",
    select_image_file: "फाइल का चयन करें",
    status_timeline: "status time-line",
    search_crop: "फसल खोजें...",
    all_categories: "सभी",
    grains: "अनाज",
    pulses: "दालें",
    vegetables: "सब्जियां",
    oilseeds: "तिलहन",
    commercial_crops: "व्यावसायिक फसलें",
    msp_rate_label: "सरकारी एमएसपी",
    demo_price_label: "बाजार मूल्य (अंदाज़ा)",
    prototype_price_data: "बाजार मूल्य की जानकारी",
    payment_expected_payout: "अपेक्षित भुगतान",
    payment_transaction_ref: "लेनदेन संदर्भ संख्या",
    payment_timeline: "भुगतान समयरेखा",
    weigh_in_completed: "तौल पूर्ण",
    payment_initiated: "भुगतान शुरू किया गया",
    untranslated_notice: "यह केवल डेमो के लिए है।",
    slot_booking_title: "सरकारी खरीद स्लॉट बुकिंग",
    select_registration_label: "फसल पंजीकरण का चयन करें",
    select_option_placeholder: "पंजीकरण चुनें",
    booking_restricted_title: "स्लॉट बुकिंग उपलब्ध नहीं है",
    slot_booked_receipt: "स्लॉट बुकिंग की पुष्टि हो गई है",
    weigh_in_schedule: "स्लॉट का समय",
    close: "बंद करें",
    approved_qty: "स्वीकृत मात्रा",
    select_date_label: "तारीख चुनें",
    select_time_label: "समय चुनें",
    confirm_booking_btn: "स्लॉट बुकिंग की पुष्टि करें",
    pricing_hub_title: "कृषि मूल्य और न्यूनतम समर्थन मूल्य (MSP) केंद्र",
    pricing_hub_desc: "सरकारी न्यूनतम समर्थन मूल्य (MSP) और स्थानीय बाजार मूल्य अपडेट की समीक्षा करें।",
    demo_warning_banner: "मूल्य डेटा केवल डेमो परीक्षण के लिए है।",
    price_label: "मूल्य",

    crop_paddy: "धान",
    crop_wheat: "गेहूं",
    crop_maize: "मक्का",
    crop_jowar: "ज्वार",
    crop_bajra: "बाजरा",
    crop_ragi: "रागी",
    crop_gram: "चना",
    crop_tur: "अरहर (तुअर)",
    crop_moong: "मूंग",
    crop_urad: "उड़द",
    crop_groundnut: "मूंगफली",
    crop_sunflower_seed: "सूरजमुखी के बीज",
    crop_soybean: "सोयाबीन",
    crop_sesamum: "तिल",
    crop_cotton: "कपास",
    crop_tomato: "टमाटर",
    crop_onion: "प्याज",
    crop_potato: "आलू",
    crop_chilli: "मिर्च",
    crop_turmeric: "हल्दी",

    crop_paddy_info: "प्रमुख खरीफ अनाज। सरकारी न्यूनतम समर्थन मूल्य (MSP) गारंटी।",
    crop_wheat_info: "रबी की प्रमुख फसल। सरकारी न्यूनतम समर्थन मूल्य (MSP) गारंटी।",
    crop_maize_info: "मोटा अनाज। सरकारी न्यूनतम समर्थन मूल्य (MSP)।",
    crop_jowar_info: "सूखा प्रतिरोधी ज्वार। सरकारी न्यूनतम समर्थन मूल्य (MSP)।",
    crop_bajra_info: "बाजरा अनाज। सरकारी न्यूनतम समर्थन मूल्य (MSP)।",
    crop_ragi_info: "कैल्शियम से भरपूर रागी। सरकारी न्यूनतम समर्थन मूल्य (MSP)।",
    crop_gram_info: "रबी की दाल। सरकारी न्यूनतम समर्थन मूल्य (MSP)।",
    crop_tur_info: "खरीफ की दाल। सरकारी न्यूनतम समर्थन मूल्य (MSP)।",
    crop_moong_info: "मूंग दाल। सरकारी न्यूनतम समर्थन मूल्य (MSP)।",
    crop_urad_info: "उड़द दाल। सरकारी न्यूनतम समर्थन मूल्य (MSP)।",
    crop_groundnut_info: "तिलहन फसल। सरकारी न्यूनतम समर्थन मूल्य (MSP)।",
    crop_sunflower_seed_info: "सूरजमुखी बीज। सरकारी न्यूनतम समर्थन मूल्य (MSP)।",
    crop_soybean_info: "सोयाबीन तिलहन। सरकारी न्यूनतम समर्थन मूल्य (MSP)।",
    crop_sesamum_info: "तिल की खेती। सरकारी न्यूनतम समर्थन मूल्य (MSP)।",
    crop_cotton_info: "कपास नकदी फसल। सरकारी न्यूनतम समर्थन मूल्य (MSP)।",
    crop_tomato_info: "सब्जी की फसल। बाजार मूल्य डेमो डेटा।",
    crop_onion_info: "सब्जी की फसल। बाजार मूल्य डेमो डेटा।",
    crop_potato_info: "कंद फसल। बाजार मूल्य डेमो डेटा।",
    crop_chilli_info: "मिर्च मसाला फसल। बाजार मूल्य डेमो डेटा।",
    crop_turmeric_info: "हल्दी नकदी फसल। बाजार मूल्य डेमो डेटा।",

    cat_grains: "अनाज",
    cat_pulses: "दालें",
    cat_vegetables: "सब्जियां",
    cat_oilseeds: "तिलहन",
    cat_commercial: "व्यावसायिक फसलें",
    unit_qtl: "प्रति क्विंटल",
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const savedLang = localStorage.getItem('f2g_lang') as Language;
    return (savedLang && ['en', 'te', 'hi'].includes(savedLang)) ? savedLang : 'en';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('f2g_lang', lang);
  };


  const t = (key: string): string => {
    return translations[language][key] || translations['en'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
